spring.application.name=UsageLog
spring.datasource.url=jdbc:mysql://localhost:3306/usagelog_db?serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# アプリケーション全体のログレベルをINFOにする
logging.level.root=INFO
# ログ文字コードは logback-spring.xml 側で設定する
# Windows端末表示はMS932、ファイル出力はUTF-8
logging.charset.file=UTF-8
# 存在しないパスでも例外を投げて共通エラーページへ遷移する
spring.mvc.throw-exception-if-no-handler-found=true